from . import pays
from . import ville
from . import client
from . import agence
from . import compte
from . import transfert
from . import type_piece_identite
from . import tarif
from . import res_partner
from . import res_user
from . import site
from . import operation_site
from . import compte_site
from . import operation
from . import  moceansms
from . import  search_transfert
from . import  search_transfert_revendication
