from . import ville
from . import client
from . import agence
from . import compte
from . import transfert
from . import type_piece_identite
from . import tarif
from . import res_partner
from . import res_user
from . import site
from . import operation_site
from . import compte_site
from . import moceansms
from . import search_transfert
from . import search_transfert_revendication
from . import taxes
from . import operation
from . import operation_agence
from . import operation_client_agence
from . import operation_client_compte
from . import compte_client
